language: php
php:
- '7.0'
- '5.6'
- '5.5'
- 'hhvm'
matrix:
  allow_failures:
  - php: hhvm
before_script:
- composer install --no-interaction
- if [ $(phpenv version-name) != "hhvm" ] && [ $(phpenv version-name) != "7.0" ]; then echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
- wget https://scrutinizer-ci.com/ocular.phar
script:
- "./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover"
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover
- composer check
