language: php
services:
- mongodb
php:
- '7.0'
- '5.6'
- '5.5'
- 'hhvm'
matrix:
  allow_failures:
  - php: hhvm
  - php: 7.0
before_script:
- echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- composer install --no-interaction
- wget https://scrutinizer-ci.com/ocular.phar
script:
- "./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover"
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover
- composer check
