language: php
php:
- '7.0'
- '5.6'
- '5.5'
- 'hhvm'
before_script:
- composer install --no-interaction
- wget https://scrutinizer-ci.com/ocular.phar
script:
- "./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover"
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover
- composer check
